# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 基本站点信息
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
site_name: 我的笔记网站
site_url: https://yjw-000.github.io/NoteStack/
repo_url: https://github.com/yjw-000/NoteStack/
repo_name: yjw-000/NoteStack
edit_uri: edit/main/docs/            # “编辑此页”按钮链接到 docs 目录
site_description: “这里是我的学习笔记”
site_author: “wyzs”

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 目录与静态资源目录
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
docs_dir: docs                       # 放 Markdown 文件的目录
site_dir: site                       # mkdocs build 输出目录

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Markdown 扩展，支持目录、公式、代码高亮...
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

markdown_extensions:
  # === 从这里开始到下面，是 pymdown-extensions 库的 markdown_extensions 配置 ===
  # 需求：pip install pymdown-extensions （不过一般应该都装了）
 
  - pymdownx.keys # 按键高亮，类似于行内代码那种，如 <kbd>Ctrl</kbd>，或者带图标的格式（强制小写）++ctrl++，也可组合 ++ctrl+s++（推荐第二种方式，第二种自带图标）
  - pymdownx.mark # 允许文本下划线，即 ^^Text^^
  - pymdownx.caret # 允许文本高亮，即 ==Text==
  - pymdownx.tilde # 允许文本删除线，即 ~~Text~~
  - pymdownx.details # 允许提示框与文本左右布局，而非原来的上下布局，如 !!! note inline "Hint"（左），!!! note inline end（右）
  - pymdownx.snippets # 允许外联任何内容
  - pymdownx.striphtml # 去除 HTML 中不需要的注释和 / 或标记属性，可减小 HTML 大小
  - pymdownx.smartsymbols # 允许上下标，如 x^2^（x²）
  - pymdownx.inlinehilite # 支持行内代码块高亮，如 `#!python range()`
  - pymdownx.smartsymbols # 智能符号，如 (c) 就是 ©️
 
  - pymdownx.b64 # 允许使用 base64 编码嵌入本地 PNG、JPEG 和 GIF 图像引用（pymdownx 支持，mkdocs 暂时不支持）
  - pymdownx.escapeall # 允许使用反斜杠（pymdownx 支持，mkdocs 貌似部分支持，不完全支持）
  - pymdownx.magiclink # 自动识别超链接（pymdownx 支持，mkdocs 暂时不支持）
  - pymdownx.progressbar # 允许进度条语法（pymdownx 支持，mkdocs 暂时不支持）
  - pymdownx.saneheaders # “#title” 也是标题，虽然中间没有空格（pymdownx 支持，mkdocs 暂时不支持）
 
  - pymdownx.blocks.tab # 支持更高级的标签块写法（危：可能与 pymdownx.tabbed 冲突）
  - pymdownx.blocks.html # 支持一些更高级的 md 内嵌 HTML 语法（pymdownx.blocks 默认开启）
  - pymdownx.blocks.details # 支持更高级的提示框布局（危：可能与 pymdownx.details 冲突）
  - pymdownx.blocks.admonition # 支持更高级提示框语法（危：可能与 admonition 冲突）
  - pymdownx.blocks.definition # 支持更高级的定义块语法（危：可能与 def_list）
 
  - pymdownx.arithmatex: # 允许数学表达式，即 $$y=x+1$$，或行内的 $x=1$
      generic: true
 
  - pymdownx.betterem: # 允许斜体和加粗
      smart_enable: all
 
  - pymdownx.critic: # 允许批注，批注详情见 https://mkdoc-material.llango.com/reference/formatting/
      mode: view # 批注模式，可为 view，accept 和 reject，不懂干啥的
 
  - pymdownx.highlight: # 允许代码块语法高亮
      use_pygments: true # 使用 pygments 而不是 javascript，啥意思不懂
      linenums: true # 全部显示行号，若为 false，也可指定起始行号，如 ```python linenums="2"，也可指定高亮行，如 hl_lines="2-3"
      linenums_style: pymdownx-inline # 行号样式 pymdownx-inline 或者 inline 和 table（最好不要使用其它的值，会有 bug，如代码复制按钮错位）
      anchor_linenums: true # 用锚链接包装代码行号，便于超链接和共享（就是行号可以像锚点一样被点击）
      line_spans: __span # 这对于行突出显示等功能正常工作至关重要，不懂
      pygments_lang_class: true # 对于自定义注释标记的功能至关重要，不懂
      # auto_title: true # 自动为所有代码块添加一个标题
 
  - pymdownx.emoji: # 允许 Emoji 表情
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
 
  - pymdownx.superfences: # 允许各种嵌套
      custom_fences:
        - name: mermaid # 允许 mermaid 图表语法
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 不清楚干啥的
 
 
  - pymdownx.tabbed: # 允许块（如代码块）添加标签，实现多语言等效果
      alternate_style: true # 唯一支持的样式，不打开等于用不了
      combine_header_slug: true # 后面的不知道干啥的
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
 
  - pymdownx.tasklist: # 允许 Todo 列表清单
      custom_checkbox: true # 允许修改其样式，不然用默认样式就很丑
      clickable_checkbox: true # 是否可通过点击切换状态（但无实际更改，只有视觉效果）
 
  # === 从这里开始到下面，是 Python-Markdown（MkDocs 默认的） 的 markdown_extensions 配置 ===
 
  - meta # 允许元标记，页面源代码顶上那几行被横线保住的内容就是元标记，为了支持某些功能使用
  - abbr # 允许文本悬浮提示，就是 ToolTip，例如：*[Text]: 啊吧啊吧
  - tables # 允许用简单语法创建表格
  - smarty # 貌似是为了提高兼容性的，不太清楚
  - def_list # 允许“定义列表”的语法，详细见 https://mkdoc-material.llango.com/reference/lists/
  - attr_list # 允许给 md 元素增加 HTML 和 CSS 属性，如一个按钮 [Subscribe to our mailing list](#){: .md-button }，甚至图标，详细见 https://mkdoc-material.llango.com/reference/buttons/
  - wikilinks # 支持快捷链接语法，例如 [[a link]]，会变成 ./a_link/
  - admonition # 允许各种各样的提示框，或代码框，样式见 https://mkdoc-material.llango.com/reference/admonitions/
  - md_in_html # 允许 md 内嵌在 HTML 中
  - sane_lists # 理智列表，避免旧版 md 抽风（强烈推荐开启）
  # - nl2br # 换行符硬断裂，即文本不像旧版 md 那样，可以直接换行
  # - codehilite # 被 pymdownx 相关扩展取代了，不建议使用这个
  # - fenced_code # 被 pymdownx 相关扩展取代了，不建议使用这个
 
  - footnotes: # 允许脚注
      BACKLINK_TITLE: 返回脚注 {} # 底部脚注的提示词，建议改一下，默认是英文的
      # SUPERSCRIPT_TEXT: {} # 脚注名称，默认就是 {}，表示标号
 
  - toc: # 目录设置
      title: 目录 # 在右侧导航侧边栏中设置目录的标题
      permalink_title: 点击定位到锚点 # 设置锚点链接的提示词
      permalink: "#" # 启用目录锚点，并设置符号为 “#”
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify # 这啥玩意儿，不懂，抄官网的
        kwds:
          case: lower

  
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 主题配置：Material for MkDocs
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
theme: # 主题设置
  name: material # 第三方主题名称
  custom_dir: docs/overrides # 覆盖部分原来的主题（重载目录）
  language: zh # material 语言
  features:
    # - header.autohide # 顶栏自动隐藏
    - content.tooltips # 提示框（以前有的样式变好看了，此外还支持更高级的提示框语法）
    - content.code.copy # 例如：``` python { .yaml .copy } 默认开启，{ .yaml .no-copy } 关闭
    - content.code.annotate # 允许内联代码注释
    - content.tabs.link # 同样的标签，整个网站的同步切换，如 C -> C++，则其它类似的全部标签都同步切换
    - content.action.edit # 允许页面被编辑（会出现编辑按钮）
    - content.action.view # 允许查看页面的源代码（会出现查看源代码按钮）
    - announce.dismiss # 公告栏可以被关闭
    # - navigation.expand # 左侧边栏节点默认全部展开（与 navigation.prune 不兼容）
    # - navigation.prune # 左侧栏节点至多展开一个，以此来减小站点的构建大小（对于页数100+的网站很有用，但是！与 navigation.expand 不兼容）
    - navigation.tabs # 页面顶部导航栏
    - navigation.footer # 页面底下换页的支持
    - navigation.indexes # 左侧边栏大节点是否可以被导向到 index.md
    - navigation.instant # 页面不会重复加载（已加载页面不会再次加载）
    - navigation.instant.progress # 加载速度慢时，在页面顶部显示加载进度（400ms 以上加载时间才会显示它）
    # - navigation.tabs.sticky # 导航栏标题栏位置固定
    # - navigation.sections # 左侧边栏节点是否保持展开
    - navigation.top # 回到顶部的按钮
    - navigation.tracking # 锚点跟踪
    - search.share # 搜索栏分享按钮
    - search.suggest # 搜索栏内容建议
    - search.highlight # 搜索栏内容高亮
    - toc.follow # 锚点关注，侧边栏自动滚动，使锚点总是可见
    # - toc.integrate # 右边侧栏是否集成到左侧边栏
  palette: # 界面整体样式
    - media: "(prefers-color-scheme)" # 系统主题
      toggle: # 切换按钮
        icon: material/theme-light-dark # 图标
        name: 切换至明亮主题 # 提示词
    - media: "(prefers-color-scheme: light)" # 亮色主题
      scheme: default
      # primary: grey # 标题栏颜色（建议自定义 CSS 调整，因为 footer 不会被此参数影响！）
      accent: purple # 链接高亮颜色
      toggle:
        icon: material/weather-sunny
        name: 切换至暗黑主题
    - media: "(prefers-color-scheme: dark)" # 暗色主题
      scheme: slate
      primary: black
      # accent: yellow
      toggle:
        icon: material/weather-night
        name: 切换至系统主题
  font: false # 避免从谷歌加载字体导致网页加载变慢（具体参数可以在自定义 CSS 中指定）
  logo: logo.png # 页面左上角徽标
  favicon: logo.png # 网页的图标
  icon: # 图标重载，替换掉默认的图标
    previous: fontawesome/solid/angle-left # 左下角向前翻页的图标
    next: fontawesome/solid/angle-right # 右下角向后翻页的图标
    repo: fontawesome/brands/github # 右上角仓库图标
    edit: material/pencil # 页面编辑的图标
    view: material/eye # 页面查看源代码的图标
    # annotation: material/arrow-right-circle # 提示按钮的图标，详细操作见 https://squidfunk.github.io/mkdocs-material/reference/annotations/#in-content-tabs-tab-1


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 插件：启用全站搜索
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
plugins:
  - search


extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 网站导航结构（左侧一级目录）
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
nav:
  - 首页: index.md
  - 学习笔记:
      - 笔记概览: notes.md
      - 数学相关:
          - 高数: 
            - 第一章: math/calculus/first.md
          - 线代: 
            - 第一章: math/linear-algebra/determinant.md
          - 概率论与数理统计:
            - 第一章: math/PTMS/first.md 
      - 算法相关:
          - 数据结构: 
            - 第一章: algorithm/data-structure/first.md
      - 系统相关:
          - 计算机组成: 
            - 第一章: computer-systems/computer-organization/first.md
          - 操作系统: 
            - 第一章: computer-systems/operating-system/first.md
          - 计算机网络: 
            - 第一章: computer-systems/computer-network/first.md
  - 关于我: about.md

